version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3005:1000" 
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host"]
